version: "3.8"
services:
  app:
    container_name: app-container
    hostname: app-server
    build: ./docker/python
    volumes:
      - ./src:/workspace
    ports:
      - 8000:8000
    restart: always
    tty: true
    depends_on:
      - db

  db:
    container_name: db-container
    hostname: db-server
    build: ./docker/mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-store-volume:/var/lib/mysql
    ports:
      - 3307:3306
    restart: always

volumes:
  db-store-volume:
    name: django_app_data
    driver: local